# Arquivo gerado por generate_unique_leagues.py
# Para atualizar, edite leagues.txt e rode: python3 generate_unique_leagues.py

LEAGUES = ['Brazil Serie A',
 'Algeria Ligue 1',
 'Mexico Liga de Expansión MX',
 'Scotland Premiership',
 'Saudi Arabia Division 1',
 'France National',
 'France Ligue 1',
 'England National League',
 'Spain Tercera - Group 16',
 'Spain Tercera - Group 9',
 'Paraguay Division 1',
 'Panama Lpf',
 'Norway 3. Division - Group 5',
 'Poland 3. Liga - Group 4',
 'Montenegro First League',
 'USA MLS Next Pro',
 'Azerbaijan Premier League',
 'Argentina Copa Argentina',
 'Finland Veikkausliiga',
 'Sweden Ettan: South',
 'Romania Liga 2',
 'Italy Serie D: Girone D',
 'Italy Serie C: Girone A',
 'Turkey U19 Elit A',
 'Paraguay Division Intermedia',
 'South America Copa Sudamericana',
 'Sweden Division 2: Vastra Gotaland',
 'Zambia Super League',
 'Georgia Crystalbet Erovnuli Liga',
 'Italy Serie D: Girone A',
 'Latvia Virsliga',
 'U21 Divisie 4',
 'Cyprus 1. Division',
 'Turkey Cup',
 'Uruguay Segunda Division',
 'Switzerland 1.Liga Promotion',
 'Spain Segunda Division RFEF: Group 5',
 'Italy Serie D: Girone H',
 'Bolivia Liga De Futbol Prof',
 'Turkey 2. Lig: Kirmizi',
 'Brazil Brasileiro Feminino A2',
 'Ireland Republic Leinster Senior League',
 'England Non League Premier: Southern South',
 'Ghana Premier League',
 'Japan Nadeshiko League 1',
 'Serbia Prva Liga',
 'Poland 2. Liga East',
 'South Africa Premier League',
 'Switzerland 1.Liga Classic',
 'Slovakia 3. Liga - East',
 'Spain Tercera - Group 10',
 'Norway Toppserien',
 'France Championnat National U19',
 'Italy Serie D: Girone B',
 'Peru Segunda Division',
 'Hungary Merkantil Bank Liga',
 'Poland 3. Liga - Group 3',
 'England Non League Premier: Isthmian',
 'Georgia Liga 3',
 'Spain Tercera - Group 15',
 'Finland Cup',
 'Spain La Liga',
 'Turkey 3. Lig: Group 2',
 'Faroe Islands Meistaradeildin',
 'Spain Division De Honor Juvenil - Group 5',
 'USA US Open Cup',
 'Bahrain Second Division',
 'Slovakia Slovakia Cup',
 'Spain La Liga 2',
 'Serbia U19 League',
 'Norway 3. Division - Group 3',
 'Turkey Super Lig',
 'Australia W-League',
 'South America Copa Libertadores U20',
 'Jamaica Premier League',
 'Spain Primera Federación Femenina',
 'Czech Republic 3. Liga MSFL',
 'Czech Republic 4. Liga Division F',
 'France CFA Group A',
 'Sweden Division 2: Norra Svealand',
 'Uruguay Primera Division',
 'Ukraine Ukrainian Cup',
 'Austria Landesliga: Burgenland',
 'England Premier League',
 'Turkey 2. Lig: Beyaz',
 'Brazil Copa do Nordeste',
 'Andorra Primera División',
 'Ukraine Premier League',
 'Spain Segunda Division RFEF: Group 4',
 'Tunisia Ligue 2',
 'Sweden Division 2: Norra Gotaland',
 'Jordan Premier League',
 'Brazil Pernambucano 1',
 'Greece Gamma Ethniki Group 2',
 'Asia Cup Women',
 'Super Lig Women',
 'Sweden Svenska Cupen Women',
 'Australia Npl Tasmania',
 'Estonia Esiliiga A',
 'England Non League Premier: Southern Central',
 'Czech Republic 4. Liga Division A',
 'Tunisia Tunisia Cup',
 'Australia New South Wales NPL Women',
 'Greece Panelinio Protathlima',
 'Poland Central Youth League',
 'Wales FAW Championship',
 'Romania 3. Liga: Series 6',
 'Australia Queensland Premier League',
 'Norway 3. Division - Group 4',
 'Netherlands Eredivisie Women',
 'Germany 3. Liga',
 'Ecuador Liga Pro',
 'England League One',
 'Germany Bundesliga',
 'Brazil Copa do Brasil Feminino',
 'Indonesia Liga 1',
 'Spain Primera Division RFEF: Group 1',
 'Spain Primera Division Women',
 'Brazil Serie C',
 'Switzerland Challenge League',
 'Singapore S. League',
 'Denmark First Division',
 'Portugal Segunda Liga',
 'Denmark Superliga',
 'Italy Serie C Play-offs',
 'Australia Npl South Australian',
 'France Ligue 2',
 'Sweden Superettan',
 'Australia Npl Victoria',
 'Belgium Reserve Pro League',
 'Macao Primeira Division',
 'Australia Northern Territory Premier League',
 'Belgium Challenger Pro League',
 'Brazil Brasileiro Women',
 'England League Two',
 'Norway 3. Division - Group 1',
 'Norway 3. Division - Group 2',
 'Portugal Liga 3',
 'Thailand Thai Premier League',
 'UEFA U19 Championship Women Qualification',
 'Iceland Pepsideild',
 'Poland 3. Liga - Group 1',
 'Australia A-League',
 'Finland Kolmonen - Etelä',
 'Italy Primavera 2',
 'Australia Capital Territory',
 'Hungary OTP Bank Liga',
 'Australia South Australia Reserves Premier League',
 'Korea Republic K League 2',
 'Australia Northern NSW NPL Women',
 'Iceland 4. Deild',
 'Paraguay Division Profesional Reserva',
 'UAE League']
